"use strict";
require('./Help');
require('./MineData');
require('./Save');
require('./AutoMine');
require('./SellData');
require('./BuyData');
require('./BuyCommand');
require('./Load');
require('./CurrentStorage');
require('./Reset');
require('./Version');
require('./Upgrade');
require('./Alias');
